site_name: My Docs
docs_dir: docs
copyright: Copyright &copy; 2026 User
site_url: https://omkargharat.github.io
theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/pine-tree
        name: Switch to Deep Space
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to Ocean Night
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/water
        name: Switch to Forest
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - navigation.footer
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
plugins:
  - search
  - macros
  # - toggle-sidebar:
  # toggle_button: navigation
  # - simple-hooks:
  # on_config: "hooks:inject_nav" # calls a function named inject_nav in hooks.py
extra:
  generator: false
